
name: Docker Build

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Git checkout
      uses: actions/checkout@v3 
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1 
    - name: Build ubuntu-22.04 small cuda 11.7
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64
        push: false
        tags: ubuntu-22.04-cuda-11.7
        file: gen/Dockerfile.ubuntu-22.04-cuda-11.7 
